name: Build packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { os: macos-latest, arch: x64, python-arch: x64, name: macos-latest }
          - { os: ubuntu-latest, arch: x64, python-arch: x64, name: ubuntu-latest }
          - { os: windows-latest, arch: x64, python-arch: x64, name: windows-latest }
          - { os: windows-latest, arch: ia32, python-arch: x86, name: windows-latest-32 }

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: ${{ matrix.config.python-arch }}
      - name: Install Excalibur
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          python -m pip install .
      - name: Build with PyInstaller on Ubuntu and MacOS
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          pyinstaller --onefile --hidden-import="pkg_resources.py2_warn" --add-data "excalibur/www/templates:excalibur/www/templates" --add-data "excalibur/www/static:excalibur/www/static" --add-data "excalibur/config_templates:excalibur/config_templates" --name "excalibur-${{ matrix.config.os }}-${{ matrix.config.arch }}" arthur.py
      - name: Build with PyInstaller on Windows
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile --hidden-import="pkg_resources.py2_warn" --add-data "excalibur/www/templates;excalibur/www/templates" --add-data "excalibur/www/static;excalibur/www/static" --add-data "excalibur/config_templates;excalibur/config_templates" --name "excalibur-${{ matrix.config.os }}-${{ matrix.config.arch }}" arthur.py
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: excalibur-${{ matrix.config.os }}-${{ matrix.config.arch }}
          path: dist/
